pub mod audio_plugin;
pub mod call_event_plugin;
pub mod camera_plugin;
pub mod character_select_plugin;
pub mod decision_plugin;
pub mod diagnostics_plugin;
pub mod drilling_plugin;
pub mod end_plugin;
pub mod player_movement_plugin;
